// Generated by CoffeeScript 1.9.1
(function() {
  var client, dhcpjs, discover, pkt, util;

  util = require('util');

  dhcpjs = require('dhcpjs');

  client = new dhcpjs.Client;

  client.on('message', function(pkt) {
    return console.log('message:', util.inspect(pkt, false, 3));
  });

  client.on('dhcpOffer', function(pkt) {
    return console.log('dhcpOffer:', util.inspect(pkt, false, 3));
  });

  client.on('dhcpAck', function(pkt) {
    return console.log('dhcpAck:', util.inspect(pkt, false, 3));
  });

  client.on('dhcpNak', function(pkt) {
    return console.log('dhcpNak:', util.inspect(pkt, false, 3));
  });

  client.on('listening', function(addr) {
    return console.log('listening on', addr);
  });

  client.bind('0.0.0.0', 68, function() {
    return console.log('bound to 0.0.0.0:68');
  });

  pkt = {
    xid: 0x01,
    chaddr: '00:88:65:39:2a:7c',
    options: {
      dhcpMessageType: dhcpjs.Protocol.DHCPMessageType.DHCPDISCOVER,
      clientIdentifier: 'MyMachine'
    }
  };

  discover = client.createDiscoverPacket(pkt);

  client.broadcastPacket(discover, void 0, function() {
    return console.log('dhcpDiscover: sent');
  });

}).call(this);
